name: Build and deploy Node.js app to Azure Web App - turbotest2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Create a temp folder and copy contents of apps/accounts-site into it
      - name: Copy app to temp folder
        run: |
          mkdir -p /tmp/accounts-site
          cp -r apps/accounts-site/* /tmp/accounts-site/

      # Install dependencies and build with Turbo in the temp folder
      - name: Install dependencies and build in temp folder
        run: |
          cd /tmp/accounts-site
          npm install
          npm run build

      # List files before zipping
      - name: List files before zipping
        run: |
          echo "Listing contents of /tmp/accounts-site:"
          ls -l /tmp/accounts-site

      # Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          cd /tmp/accounts-site
          zip -r release.zip ./* .next -qr

          # List files inside the zip file
          echo "Listing files inside the zip file:"
          unzip -l release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: /tmp/accounts-site/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BCE68A5B54194C33800E6E39BFF4450C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_18B5A2DA2765443A843F2B2ED20CAA07 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8957526655E4DB69C90F026ECFE032B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'turbotest2'
          slot-name: 'Production'
          package: './'  # The correct package path to the app folder
